name: Publish to Docker Hub
on:
  push:
    tags: [s-*]
       # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: itoktsnhc/jobtracker
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ./JobTrackerX.WebApi/Dockerfile
          tag_names: true
