name: CI to Docker Hub
on:
  push:
    tags: [s-*]
       # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          include-prerelease: true
      - run: dotnet publish  ./JobTrackerX.WebApi/JobTrackerX.WebApi.csproj -c Release -o ./release
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: itoktsnhc/jobtracker
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: ./release
          tag_names: true
