name: CI to Docker Hub
on:
  push:
    tags: [server/*]
       # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
      - run: dotnet publish  ./JobTrackerX.WebApi/JobTrackerX.WebApi.csproj -c Release -o ./release
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "server:/(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: itoktsnhc/jobtracker
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: ./release
          tag_names: true